/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OdoGUI.java
 *
 * Created on 21/04/2011, 02:33:19 PM
 */
package Odometer.GUI;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author User
 */
public class OdoGUI extends javax.swing.JFrame {

    /** Creates new form OdoGUI */
    public OdoGUI() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        ImageIcon icon = new ImageIcon(getClass().getResource("/Odometer/GUI/lbesa.gif"));
        setIconImage(icon.getImage());
        setTitle("Odometer");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPBackground1 = new javax.swing.JPanel();
        jPBackground2 = new javax.swing.JPanel();
        jLValue = new javax.swing.JLabel();
        jLKm = new javax.swing.JLabel();
        jLState = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPBackground1.setBackground(new java.awt.Color(204, 0, 51));

        jPBackground2.setBackground(new java.awt.Color(0, 0, 0));

        jLValue.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 18));
        jLValue.setForeground(new java.awt.Color(255, 255, 255));
        jLValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLValue.setText("00 00 00");

        jLKm.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLKm.setForeground(new java.awt.Color(255, 255, 255));
        jLKm.setText("km");

        jLState.setForeground(new java.awt.Color(255, 153, 51));
        jLState.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPBackground2Layout = new javax.swing.GroupLayout(jPBackground2);
        jPBackground2.setLayout(jPBackground2Layout);
        jPBackground2Layout.setHorizontalGroup(
            jPBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBackground2Layout.createSequentialGroup()
                .addComponent(jLState, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLValue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLKm, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPBackground2Layout.setVerticalGroup(
            jPBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBackground2Layout.createSequentialGroup()
                .addComponent(jLState, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLKm, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE))
            .addComponent(jLValue, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPBackground1Layout = new javax.swing.GroupLayout(jPBackground1);
        jPBackground1.setLayout(jPBackground1Layout);
        jPBackground1Layout.setHorizontalGroup(
            jPBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBackground1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPBackground2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPBackground1Layout.setVerticalGroup(
            jPBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBackground1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPBackground2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBackground1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBackground1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLKm;
    private javax.swing.JLabel jLState;
    private javax.swing.JLabel jLValue;
    private javax.swing.JPanel jPBackground1;
    private javax.swing.JPanel jPBackground2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    /**
     * Gets the value lable.
     *
     * @return Value lable.
     */
    public JLabel getjLValue() {
        return jLValue;
    }

    /**
     * Gets the state lable.
     *
     * @return State lable.
     */
    public JLabel getjState() {
        return jLState;
    }
}
