/*
 * @(#)TableTennisView.java 2.0	11/01/11
 *
 * Copyright 2011, Pontificia Universidad Javeriana, All rights reserved.
 * Takina and SIDRe PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */
package Presentation;

import Abstraction.Ball;
import Abstraction.DEF;
import javax.swing.ImageIcon;

/**
 * This class represents GUI.
 *
 * @author  SIDRe - Pontificia Universidad Javeriana
 * @author  Takina  - Pontificia Universidad Javeriana
 * @version 2.0, 11/01/11
 * @since   JDK1.0
 */
public class TableTennisView extends javax.swing.JFrame implements GUIObserver {

    /** 
     * Creates new form TableTennisView
     */
    public TableTennisView() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        ImageIcon icon = new ImageIcon(getClass().getResource("/Presentation/lbesa.gif"));
        setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPtable = new Presentation.Table("/Presentation/table.png");
        jLball = new javax.swing.JLabel();
        jLagentA = new javax.swing.JLabel();
        jLagentB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agent Ping-Pong");

        jPtable.setBackground(new java.awt.Color(102, 153, 0));
        jPtable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLball.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentation/ball.gif"))); // NOI18N

        jLagentA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentation/agentA.gif"))); // NOI18N

        jLagentB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentation/agentB.gif"))); // NOI18N

        javax.swing.GroupLayout jPtableLayout = new javax.swing.GroupLayout(jPtable);
        jPtable.setLayout(jPtableLayout);
        jPtableLayout.setHorizontalGroup(
            jPtableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPtableLayout.createSequentialGroup()
                .addComponent(jLagentA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLball, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(483, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPtableLayout.createSequentialGroup()
                .addContainerGap(508, Short.MAX_VALUE)
                .addComponent(jLagentB))
        );
        jPtableLayout.setVerticalGroup(
            jPtableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPtableLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLagentA)
                .addContainerGap(216, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPtableLayout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(jLball)
                .addGap(101, 101, 101)
                .addComponent(jLagentB)
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPtable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPtable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLagentA;
    private javax.swing.JLabel jLagentB;
    private javax.swing.JLabel jLball;
    private javax.swing.JPanel jPtable;
    // End of variables declaration//GEN-END:variables

    public void distributedChangueModel(Ball ball, double[] playerPV) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void localChangueModel(Ball ball, DEF player, double[] playerPV) {
        if (DEF.PLAYER_A.equals(player)) {
            jLagentA.setLocation((int) playerPV[0], (int) playerPV[1]);
        } else {
            jLagentB.setLocation((int) playerPV[0], (int) playerPV[1]);
        }
        jLball.setLocation((int) ball.getPV()[0], (int) ball.getPV()[1]);
    }
}
